# Generated by Django 5.1 on 2024-08-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_username', models.CharField(max_length=100, unique=True)),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
    ]
