# Generated by Django 5.1 on 2024-08-29 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='taluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taluka', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.state')),
            ],
        ),
    ]
