# Generated by Django 5.1 on 2024-09-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_dropoutstudentdata_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropoutstudentdata',
            name='reason',
            field=models.CharField(choices=[('Academic Challenges', 'Academic Challenges'), ('Financial Issues', 'Financial Issues'), ('Family Issues', 'Family Issues'), ('Health Problems', 'Health Problems'), ('Lack of Interest', 'Lack of Interest'), ('Poor School Environment', 'Poor School Environment'), ('Employment', 'Employment'), ('Educational Opportunities', 'Educational Opportunities'), ('Transportation Issues', 'Transportation Issues'), ('Personal Issues', 'Personal Issues'), ('Relocation', 'Relocation'), ('Bullying', 'Bullying'), ('Inadequate Infrastructure', 'Inadequate Infrastructure'), ('Cultural or Religious Reasons', 'Cultural or Religious Reasons'), ('Language Barriers', 'Language Barriers'), ('Legal Issues', 'Legal Issues'), ('Substance Abuse', 'Substance Abuse'), ('Safety Concerns', 'Safety Concerns'), ('Academic Performance Pressure', 'Academic Performance Pressure'), ('Lack of Parental Support', 'Lack of Parental Support'), ('School Fees', 'School Fees'), ('None', 'None')], max_length=100),
        ),
    ]
